dbHost = 'localhost'
dbName = 'locations'
dbPassword = "password"
dbUser = 'owntracks-pg-recorder'
databaseMigrationsPath = 'databasemigrations/'
reverseGeocodeApiUrl = ''
geocodeApiUrl = ''
port = 3030
MQTTURL = 'mqtt://localhost:1883'
MQTTUsername = 'owntracks-pg-recorder'
MQTTPassword = ""
Debug = true
FilterUsers = ""
DefaultUser = ""
